package com.sena.mysqlwithjpa.controller;

import com.sena.mysqlwithjpa.entity.User;
import com.sena.mysqlwithjpa.repository.UserRepository;
import jakarta.validation.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.Set;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    private static final Logger log = LoggerFactory.getLogger(MainController.class);
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;
    // Creamos una instancia para las validaciones
    @Autowired
    private ValidatorFactory validatorFactory;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        //Agregamos logs al método
        log.info("Intentando agregar usuario: name={}, email={}",name,email);

        // Creamos el objeto que nos dará métodos para obtener la validación de User
        Validator validator = validatorFactory.getValidator();

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        // Validamos el objeto n con todas las validaciones que tenemos en la clase User
        Set<ConstraintViolation<User>> violations = validator.validate(n);

        if (!violations.isEmpty()) {
            // juntamos el primer mensaje de error para devolverlo
            String mensaje = violations.iterator().next().getMessage();
            throw new ConstraintViolationException(mensaje, violations);
        }

        userRepository.save(n);
        log.info("Usuario guardado exitosamente: name={}", name);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {

        //Agregamos logs al método
        log.info("Solicitando la lista de todos los usuarios registrados");

        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}